/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.digimaxx.telas;

import static br.com.digimaxx.telas.Principal.jPrincipal;
import br.com.digimaxx.utilitarios.Cliente;
import br.com.digimaxx.utilitarios.Pagamentos;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.Date;


public class CadastroPagamentos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    Date mes = new Date();
    SimpleDateFormat banco = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat m = new SimpleDateFormat("yyyy-MM");
    SimpleDateFormat formatarTabela = new SimpleDateFormat("dd/MM/yyyy");
        
    
    //    VARIAVEIS DO SISTEMA
    int fornId;
    String Pag = "N";
    String cheque = "N";
    String tipo = null;
    String[] colunas = null;
    String sqlBusca = null;
    int pagId;
    
    //    Instanciar classes para a busca de informações
    Pagamentos pagamento = new Pagamentos();
    Cliente clientes = new Cliente();
    
    /**
     * Creates new form TelaCadastroPagamentos
     */
    public CadastroPagamentos() {
        initComponents();
        pagamento.verificarTabela();
        ArrayList<Cliente> lista = clientes.ordenar();
        for(Cliente f: lista){
            cboFornecedor.addItem(f.getNome());
        }
        txtDoc.requestFocus();
    }
    private void limparCampos(){
            txtCodigo.setText(null);    
            jDataEnt.setDate(null);
            jDataVenc.setDate(null);
            fornId = 0;
            cboFornecedor.setSelectedIndex(0);
            txtDoc.setText(null);
            Pag = "N";
            rbtS.setSelected(false);
            rbtN.setSelected(true);
            jDataPag.setDate(null);
            txtValor.setText(null);
            txtValorPago.setText(null);
            cheque = "N";
            jcCheque.setSelected(false);
            jParcelas.setValue(1);
    }
    
   private void parcelas(){     
       int p = Integer.parseInt(jParcelas.getValue().toString());
       Calendar c = Calendar.getInstance();
       c.setTime(jDataEnt.getDate());
       for(int i=1; i <= p; i++){
        c.set(Calendar.MONTH, c.get(Calendar.MONTH) + 1);
        pagamento.cadastrarParcelas(banco.format(jDataEnt.getDate()), banco.format(c.getTime()),String.valueOf(i)+"/"+String.valueOf(p), 
               fornId, Double.parseDouble(txtValor.getText().replace("R$ ", "").replace(",", ".")), Double.parseDouble(txtValorPago.getText().replace("R$ ", "").replace(",", ".")), 
               Pag, cheque);          
       }
           JOptionPane.showMessageDialog(null, "Parcelas cadastradas com sucesso!");
          
    }
   
   private void preencherCampos(int pagId){
        txtCodigo.setText(String.valueOf(pagId));      
        jDataEnt.setDate(pagamento.getData_entrada());
        jDataVenc.setDate(pagamento.getData_vencimento());
        clientes.pesquisaNome(pagamento.getFornId());
        cboFornecedor.setSelectedItem(clientes.getNome().toUpperCase());
        txtDoc.setText(pagamento.getPagDocumento().toUpperCase());
        if(pagamento.getPag().equals("S")){
            rbtS.setSelected(true);
            Pag = "S";
            jDataPag.setDate(pagamento.getData_pagamento());
            jDataPag.setEnabled(true);
            txtValorPago.setEditable(true);          
        }else{
            rbtN.setSelected(true);
            Pag = "N";
            jDataPag.setDate(null);
            jDataPag.setEnabled(false);
            txtValorPago.setEnabled(false);            
            jDataPag.setEnabled(false);
        }
        txtValor.setText("R$ "+String.format("%.2f", pagamento.getPagValor()));
        txtValorPago.setText("R$ "+String.format("%.2f", pagamento.getPagValor() + pagamento.getPagJuros()));
        jParcelas.setValue(1);
        if(pagamento.getCheque().equals("S")){
            jcCheque.setSelected(true);
        }else{
            jcCheque.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jDataEnt = new com.toedter.calendar.JDateChooser();
        jDataVenc = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cboFornecedor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JTextField();
        rbtS = new javax.swing.JRadioButton();
        rbtN = new javax.swing.JRadioButton();
        jDataPag = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtValorPago = new javax.swing.JTextField();
        jcCheque = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jParcelas = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Pagamentos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("Data de Entrada");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("Data de Vencimento");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtCodigo.setPreferredSize(new java.awt.Dimension(92, 35));
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jDataEnt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jDataEnt.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jDataEnt.setPreferredSize(new java.awt.Dimension(87, 35));

        jDataVenc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jDataVenc.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jDataVenc.setPreferredSize(new java.awt.Dimension(87, 35));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.blue);
        jLabel4.setText("Fornecedor");

        cboFornecedor.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        cboFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        cboFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        cboFornecedor.setPreferredSize(new java.awt.Dimension(129, 35));
        cboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFornecedorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.blue);
        jLabel5.setText("Número do Documento");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.blue);
        jLabel6.setText("Pagamento Efetuado?");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.blue);
        jLabel7.setText("Data de Pagamento");

        txtDoc.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtDoc.setPreferredSize(new java.awt.Dimension(92, 35));
        txtDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDocFocusLost(evt);
            }
        });

        rbtS.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtS);
        rbtS.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        rbtS.setText("Sim");
        rbtS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSActionPerformed(evt);
            }
        });

        rbtN.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtN);
        rbtN.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        rbtN.setSelected(true);
        rbtN.setText("Não");
        rbtN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNActionPerformed(evt);
            }
        });

        jDataPag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jDataPag.setEnabled(false);
        jDataPag.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jDataPag.setPreferredSize(new java.awt.Dimension(91, 35));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.blue);
        jLabel8.setText("Total");

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.blue);
        jLabel9.setText("Valor Pago");

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.blue);
        jLabel10.setText("Parcelas");

        txtValor.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtValor.setText("R$ 0,00");
        txtValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtValor.setPreferredSize(new java.awt.Dimension(92, 35));
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        txtValorPago.setEditable(false);
        txtValorPago.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtValorPago.setText("R$ 0,00");
        txtValorPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtValorPago.setPreferredSize(new java.awt.Dimension(92, 35));
        txtValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorPagoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorPagoFocusLost(evt);
            }
        });

        jcCheque.setBackground(new java.awt.Color(255, 255, 255));
        jcCheque.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jcCheque.setForeground(java.awt.Color.red);
        jcCheque.setText("Pagamento com folha de cheque?");
        jcCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcChequeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel16.setForeground(java.awt.Color.blue);
        jLabel16.setText("Para cadastrar parcelas, coloque a data inicial, quantidade de parcelas e o valor total. ");

        btnSalvar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/iconSave.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setFocusPainted(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setPreferredSize(new java.awt.Dimension(130, 65));
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/iconEditarMini.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnAlterar.setContentAreaFilled(false);
        btnAlterar.setFocusPainted(false);
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterar.setPreferredSize(new java.awt.Dimension(130, 65));
        btnAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/iconExcluirMini.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setFocusPainted(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setPreferredSize(new java.awt.Dimension(130, 65));
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jParcelas.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jParcelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jParcelas.setPreferredSize(new java.awt.Dimension(31, 35));
        jParcelas.setValue(1);

        jLabel17.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel17.setForeground(java.awt.Color.blue);
        jLabel17.setText("As parcelas são geradas automaticamente.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCheque)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(204, 204, 204)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(73, 73, 73)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jDataEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(83, 83, 83)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jDataVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboFornecedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(txtDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rbtS)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rbtN))
                                        .addComponent(jLabel6))))
                            .addGap(84, 84, 84)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDataPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel10)
                                        .addComponent(jParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtS)
                            .addComponent(rbtN)))
                    .addComponent(jDataPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jcCheque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFornecedorActionPerformed
        clientes.pesquisaId(cboFornecedor.getSelectedItem().toString());
        fornId = clientes.getId();
    }//GEN-LAST:event_cboFornecedorActionPerformed

    private void txtDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocFocusLost
        txtValor.requestFocus();
    }//GEN-LAST:event_txtDocFocusLost

    private void rbtSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSActionPerformed
        Pag = "S";
        jDataPag.setEnabled(true);
        txtValorPago.setEditable(true);
    }//GEN-LAST:event_rbtSActionPerformed

    private void rbtNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNActionPerformed
        Pag = "N";
        jDataPag.setEnabled(false);
        txtValorPago.setEnabled(false);
    }//GEN-LAST:event_rbtNActionPerformed

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        txtValor.setText(txtValor.getText().replace("R$ ",""));
        txtValor.selectAll();
    }//GEN-LAST:event_txtValorFocusGained

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        Double valor = Double.parseDouble(txtValor.getText().replace("R$ ","").replace(",","."));
        txtValor.setText("R$ "+String.format("%.2f", valor));
               
    }//GEN-LAST:event_txtValorFocusLost

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        txtValorPago.setText(txtValor.getText());
    }//GEN-LAST:event_txtValorKeyReleased

    private void txtValorPagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagoFocusGained
        txtValorPago.setText(txtValorPago.getText().replace("R$ ",""));
        txtValorPago.selectAll();
    }//GEN-LAST:event_txtValorPagoFocusGained

    private void txtValorPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagoFocusLost
        Double valor = Double.parseDouble(txtValorPago.getText().replace("R$ ", "").replace(",", "."));
        txtValorPago.setText("R$ "+String.format("%.2f", valor));
    }//GEN-LAST:event_txtValorPagoFocusLost

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(fornId == 0){
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor!");
        }else if(jDataEnt.getDate() == null){
            JOptionPane.showMessageDialog(null, "A data de entrada é obrigatória!");
        }else if(txtValor.getText().equals("R$ 0,00") || txtValor.getText() == null){
            JOptionPane.showMessageDialog(null, "O campo valor deve ser diferente de Zero(R$ 0,00)!");
        }else{
           final TelaProgresso carregando = new TelaProgresso();
        carregando.setVisible(true);
        Thread t = new Thread(){
            String dataPagamento = null;
            Double valorPago = 0.00;
            public void run(){
                //Gera o arquivo pdf
                try {
                  int p = Integer.parseInt(jParcelas.getValue().toString());
                  if(p == 1){
                      String dataPag = null;
                      if(jDataPag.getDate() != null){
                          dataPag = banco.format(jDataPag.getDate());
                      }
                      Double valorOriginal = Double.parseDouble(txtValor.getText().replace("R$ ", "").replace(",", ".").trim());
                      Double valorPago = Double.parseDouble(txtValorPago.getText().replace("R$ ", "").replace(",", ".").trim());
                      if(pagamento.cadastrar(
                              banco.format(jDataEnt.getDate()), 
                              banco.format(jDataVenc.getDate()), 
                              fornId, 
                              txtDoc.getText().toUpperCase(), 
                              Pag, 
                              dataPag, 
                              valorOriginal, 
                              valorPago-valorOriginal, 
                              cheque)){
                            limparCampos();  
                            carregando.dispose();
                      }else{
                          JOptionPane.showMessageDialog(null, "Erro ao cadastrar pagamento!");
                      }
                  }else{
                          parcelas();
                          limparCampos();                          
                          carregando.dispose();
                  }
                } catch (Exception e) {
                    e.printStackTrace(); // imprime no console
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR PAGAMENTO:\n" + e.getClass().getName() + "\n" + e.getMessage());
                }
            }
        };
        t.start();
        
        }    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(pagId == 0){
                JOptionPane.showMessageDialog(null, "Clique na Tabela para selecionar um pagamento.");
            }else{

        final TelaProgresso carregando = new TelaProgresso();
        carregando.setVisible(true);
        Thread t = new Thread(){
            String dataPagamento = null;
            Double valorPago = 0.00;
            public void run(){
                //Gera o arquivo pdf
                try {
                    if(Pag.equals("S")){
                       dataPagamento =  banco.format(jDataPag.getDate());
                       valorPago = Double.parseDouble(txtValorPago.getText().replace("R$ ", "").replace(",", ".")) - Double.parseDouble(txtValor.getText().replace("R$ ", "").replace(",", "."));
                    }
                    
                    if(pagamento.alterar(
                            banco.format(jDataEnt.getDate()), 
                            banco.format(jDataVenc.getDate()),
                            fornId,
                            txtDoc.getText(), 
                            Pag,
                            dataPagamento,
                            Double.parseDouble(txtValor.getText().replace("R$ ", "").replace(",", ".")),
                            valorPago,
                            cheque, 
                            pagId)){                        
                        limparCampos();                        
                        carregando.dispose();
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao gerar o PDF! \n"+e);
                }
            }
        };
        t.start();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(pagId == 0){
            JOptionPane.showMessageDialog(null, "Clique na Tabela para selecionar um pagamento!");
        }else{
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o pagamento? "+pagId, "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
        
            final TelaProgresso carregando = new TelaProgresso();
            carregando.setVisible(true);
            Thread t = new Thread(){
            public void run(){
                //Gera o arquivo pdf
                try {
                    if(pagamento.excluir(pagId)){                                                
                        limparCampos();
                        carregando.dispose();
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao gerar o PDF! \n"+e);
                }
            }
        };
        t.start();
        }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jcChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcChequeActionPerformed
        cheque = "S";
    }//GEN-LAST:event_jcChequeActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        if(!txtCodigo.getText().isEmpty()){
            pagamento.pesquisar(Integer.parseInt(txtCodigo.getText()));
            pagId = Integer.parseInt(txtCodigo.getText());
            preencherCampos(Integer.parseInt(txtCodigo.getText()));  
        }
        
    }//GEN-LAST:event_txtCodigoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboFornecedor;
    private com.toedter.calendar.JDateChooser jDataEnt;
    private com.toedter.calendar.JDateChooser jDataPag;
    private com.toedter.calendar.JDateChooser jDataVenc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jParcelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcCheque;
    private javax.swing.JRadioButton rbtN;
    private javax.swing.JRadioButton rbtS;
    public static javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables
}
