/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.digimaxx.telas;

import br.com.digimaxx.utilitarios.Categorias;
import br.com.digimaxx.utilitarios.ModeloTabela;
import java.awt.Color;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author eric
 */
public class CadastroCategorias extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form CadastroCategorias
     */
    Categorias categoria = new Categorias();
   
    
    public CadastroCategorias() {
        initComponents();
        categoria.verificarECriarTabela();
        tabelaVazia();
        txtCatNome.requestFocus();
    }
    
    private void limparCampos(){
        txtCatId.setText(null);
        txtCatNome.setText(null);
    }
    
    private void tabelaVazia() {
    ArrayList<Object[]> dados = new ArrayList<>();
    String[] colunas = new String[]{"CÓDIGO", "NOME DA CATEGORIA"};
    ArrayList<Categorias> lista = categoria.ordenaNome(); 
    
    for (Categorias i : lista) {        
        dados.add(new Object[]{
            i.getCatId(), 
            i.getCatNome()                     
        });
    }
        ModeloTabela modelo = new ModeloTabela(dados, colunas) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 1) return int.class; // checkbox na última coluna
                if (columnIndex == 2 ) return String.class;
                               
                return Object.class;
            }
        };

        tblCategoria.setModel(modelo);

        //seta o modelo da tabela pela classe modelo
        tblCategoria.setModel(modelo);
        
        //Decide se pode ou não reordenar a tabela
        tblCategoria.getTableHeader().setReorderingAllowed(true);
        
        tblCategoria.setAutoResizeMode(tblCategoria.AUTO_RESIZE_ALL_COLUMNS);
        tblCategoria.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        //ALTERA A COR DO CABEÇALHO
        Color cor = new Color(102, 102, 102);
        DefaultTableCellRenderer cabecalho = new DefaultTableCellRenderer();
        cabecalho.setBackground(cor);
        cabecalho.setForeground(Color.white);

        for (int i = 0; i < tblCategoria.getModel().getColumnCount(); i++) {
               tblCategoria.getColumnModel().getColumn(i).setHeaderRenderer(cabecalho);
        } 
        //ALTERA A COR DA BORDA DE FORA DO JSCROLLPANE
        jScrollPane1.setBorder(BorderFactory.createLineBorder(cor));
        jScrollPane1.getViewport().setBackground(Color.white);
        tblCategoria.setBackground(Color.white);
        tblCategoria.setForeground(Color.black);
        //altera tamanho das colunas da tabela
        tblCategoria.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblCategoria.getColumnModel().getColumn(0).setResizable(false);
        tblCategoria.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblCategoria.getColumnModel().getColumn(1).setResizable(false);
   
} 
    
   
    private void setar(){
        int setar = tblCategoria.getSelectedRow();
        txtCatId.setText(tblCategoria.getModel().getValueAt(setar, 0).toString());
        txtCatNome.setText(tblCategoria.getModel().getValueAt(setar, 1).toString());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCatId = new javax.swing.JTextField();
        txtCatNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpaCampos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Categorias");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("Nome da categoria");

        txtCatId.setEditable(false);
        txtCatId.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtCatId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtCatId.setPreferredSize(new java.awt.Dimension(170, 40));

        txtCatNome.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtCatNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtCatNome.setPreferredSize(new java.awt.Dimension(127, 40));
        txtCatNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCatNomeKeyReleased(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/iconSave.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setFocusPainted(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setPreferredSize(new java.awt.Dimension(170, 65));
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/iconEditarMini.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnEditar.setContentAreaFilled(false);
        btnEditar.setFocusPainted(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setPreferredSize(new java.awt.Dimension(170, 65));
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/iconExcluirMini.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setFocusPainted(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setPreferredSize(new java.awt.Dimension(170, 65));
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpaCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/iconLixeiraExcluir.png"))); // NOI18N
        btnLimpaCampos.setText("Limpar Campos");
        btnLimpaCampos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnLimpaCampos.setContentAreaFilled(false);
        btnLimpaCampos.setFocusPainted(false);
        btnLimpaCampos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpaCampos.setPreferredSize(new java.awt.Dimension(170, 65));
        btnLimpaCampos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpaCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaCamposActionPerformed(evt);
            }
        });

        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        tblCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategoria);
        if (tblCategoria.getColumnModel().getColumnCount() > 0) {
            tblCategoria.getColumnModel().getColumn(0).setMinWidth(100);
            tblCategoria.getColumnModel().getColumn(0).setMaxWidth(120);
            tblCategoria.getColumnModel().getColumn(1).setMinWidth(650);
            tblCategoria.getColumnModel().getColumn(1).setMaxWidth(650);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpaCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCatId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCatNome, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCatId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCatNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpaCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(txtCatNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite um nome para categoria.");
        }else if(!txtCatId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Categoria já cadastrada no banco de dados,\n clique em editar para salvar alterações.");
        }else{
            final TelaProgresso carregando = new TelaProgresso();
            carregando.setVisible(true);
            Thread t = new Thread(){
                public void run(){
                    //Gera o arquivo pdf
                    try {
                        sleep(2000);
                        categoria.cadastrar(txtCatNome.getText().toUpperCase());
                        limparCampos();
                        tabelaVazia();
                        carregando.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Erro: "+e);
                    }
                }
            };
            t.start();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriaMouseClicked
        setar();
    }//GEN-LAST:event_tblCategoriaMouseClicked

    private void btnLimpaCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaCamposActionPerformed
        final TelaProgresso carregando = new TelaProgresso();
            carregando.setVisible(true);
            Thread t = new Thread(){
                public void run(){
                    //Gera o arquivo pdf
                    try {
                        sleep(1000);
                        limparCampos();
                        carregando.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Erro: "+e);
                    }
                }
            };
            t.start();
    }//GEN-LAST:event_btnLimpaCamposActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(txtCatId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Clique em um item da tabela para alterar.");
        }else if(txtCatNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo nome não pode ser vazio.");
        }else{
            final TelaProgresso carregando = new TelaProgresso();
                carregando.setVisible(true);
                Thread t = new Thread(){
                    public void run(){
                        //Gera o arquivo pdf
                        try {
                            sleep(2000);
                            categoria.editar(txtCatNome.getText(), Integer.parseInt(txtCatId.getText()));
                            tabelaVazia();
                            limparCampos();
                            carregando.dispose();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Erro: "+e);
                        }
                    }
                };
                t.start();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(txtCatId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecione na tabela a categoria para excluir.");
        }else{
            int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir a categoria "+txtCatId.getText() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (confirma == JOptionPane.YES_OPTION) {
                    final TelaProgresso carregando = new TelaProgresso();
                    carregando.setVisible(true);
                    Thread t = new Thread(){
                        public void run(){
                            //Gera o arquivo pdf
                            try {
                                sleep(2000);
                                categoria.excluir(Integer.parseInt(txtCatId.getText()));
                                tabelaVazia();
                                limparCampos();
                                carregando.dispose();
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Erro: "+e);
                            }
                        }
                    };
                    t.start();
                }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCatNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCatNomeKeyReleased
        txtCatNome.setText(txtCatNome.getText().toUpperCase());
    }//GEN-LAST:event_txtCatNomeKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpaCampos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JTextField txtCatId;
    private javax.swing.JTextField txtCatNome;
    // End of variables declaration//GEN-END:variables
}
