/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.digimaxx.telas;

import br.com.digimaxx.utilitarios.FormasPagamento;
import br.com.digimaxx.utilitarios.ModeloTabela;
import java.awt.Color;
import java.awt.Dimension;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author eric
 */
public class TelaFormasPagamento extends javax.swing.JInternalFrame {
    FormasPagamento formaPagamento = new FormasPagamento();
    /**
     * Creates new form TelaFormasPagamento
     */
    
    public TelaFormasPagamento() {
        initComponents();
        if(!formaPagamento.buscaFormaPagamento()){
            formaPagamento.insereDados();  
        }
        tabelaVazia();
    }
    
    //LISTA AS FORMAS DE PAGAMENTO
    private void tabelaVazia(){                
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Nome"};
        
        ArrayList<FormasPagamento> lista = formaPagamento.listar();
            for(FormasPagamento i:lista){
               dados.add(new Object[]{
                        i.getfId(),
                        i.getfNome()                          
                      }); 
            }
       
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        //seta o modelo da tabela pela classe modelo
        tblFormaPag.setModel(modelo);
        
        //Decide se pode ou não reordenar a tabela
        tblFormaPag.getTableHeader().setReorderingAllowed(true);
        // Cabeçalho com altura de 50px
        tblFormaPag.getTableHeader().setPreferredSize(new Dimension(0, 40));
        
        tblFormaPag.setAutoResizeMode(tblFormaPag.AUTO_RESIZE_ALL_COLUMNS);
        tblFormaPag.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        //ALTERA A COR DO CABEÇALHO
        Color cor = new Color(102, 102, 102);
        DefaultTableCellRenderer cabecalho = new DefaultTableCellRenderer();
        cabecalho.setBackground(cor);
        cabecalho.setForeground(Color.white);

        for (int i = 0; i < tblFormaPag.getModel().getColumnCount(); i++) {
               tblFormaPag.getColumnModel().getColumn(i).setHeaderRenderer(cabecalho);
        } 
      
            //ALTERA A COR DA BORDA DE FORA DO JSCROLLPANE
            jScrollPane1.setBorder(BorderFactory.createLineBorder(cor));
            jScrollPane1.getViewport().setBackground(Color.white);
            tblFormaPag.setBackground(Color.white);
            tblFormaPag.setForeground(Color.black);
            //altera tamanho das colunas da tabela
            tblFormaPag.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblFormaPag.getColumnModel().getColumn(0).setResizable(false);
            tblFormaPag.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblFormaPag.getColumnModel().getColumn(1).setResizable(false);
            
    }
    
    //SELECIONA O ITEM DA TABELA PARA EXCLUSÃO
    private void setar(){
        int setar = tblFormaPag.getSelectedRow();
        txtFid.setText(tblFormaPag.getModel().getValueAt(setar, 0).toString());  
        txtFid.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFid = new javax.swing.JTextField();
        txtFnome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFormaPag = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tipos de pagamento");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("Forma de Pagamento");

        txtFid.setEditable(false);
        txtFid.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtFid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtFid.setPreferredSize(new java.awt.Dimension(70, 40));
        txtFid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFidFocusGained(evt);
            }
        });
        txtFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFidActionPerformed(evt);
            }
        });

        txtFnome.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtFnome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        txtFnome.setPreferredSize(new java.awt.Dimension(70, 40));

        btnSalvar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/Save_24x24.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setPreferredSize(new java.awt.Dimension(80, 60));
        btnSalvar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/Edit_24x24.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/Delete_24x24.png"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblFormaPag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFormaPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFormaPagMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFormaPag);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtFid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(txtFid.getText().equals("")){
            if(txtFnome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Digite o nome da Forma de Pagamento!");
            }else{
                final TelaProgresso carregando = new TelaProgresso();
                        carregando.setVisible(true);
                        Thread t = new Thread(){
                            public void run(){
                                //Gera o arquivo pdf
                                try {
                                    sleep(2000);
                            if(formaPagamento.inserir(txtFnome.getText().toUpperCase())){
                                txtFnome.setText(null);
                                tabelaVazia();
                            }
                            carregando.dispose();
                        } catch (Exception e) {
                           JOptionPane.showMessageDialog(null, "Erro: "+e);
                        }
                            }
                        };
                        t.start();   
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblFormaPagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFormaPagMouseClicked
        setar();
    }//GEN-LAST:event_tblFormaPagMouseClicked

    private void txtFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFidActionPerformed
        
    }//GEN-LAST:event_txtFidActionPerformed

    private void txtFidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFidFocusGained
        formaPagamento.localizaId(Integer.parseInt(txtFid.getText().trim()));
        txtFnome.setText(formaPagamento.getfNome().toUpperCase());
    }//GEN-LAST:event_txtFidFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtFid.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Clique na tabela para alterar!");
        }else{
            if(formaPagamento.editar(Integer.parseInt(txtFid.getText().trim()), txtFnome.getText())){
                txtFid.setText(null);
                txtFnome.setText(null);
                tabelaVazia();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtFid.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Clique na tabela para excluir!");
        }else{
            int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir: ? "+txtFnome.getText().toUpperCase(), "Atenção", JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
            if(formaPagamento.excluir(Integer.parseInt(txtFid.getText().trim()))){
                txtFid.setText(null);
                txtFnome.setText(null);
                tabelaVazia();
            }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFormaPag;
    private javax.swing.JTextField txtFid;
    private javax.swing.JTextField txtFnome;
    // End of variables declaration//GEN-END:variables
}
