/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.digimaxx.telas;

/**
 *
 * @author eric
 */
public class TelaSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaSobre
     */
    public TelaSobre() {
        initComponents();
        insereTexto();
        insereVersao();
    }
    
    private void insereTexto(){
        pTextoSobre.setContentType("text/html");
        pTextoSobre.setText("<html>"
                + "<body>"
                + "<h1 style='color:#000080; text-align: center; font-size: 24px;'>Sistema de Automação e Gerenciamento</h1>"
                + "<p style='text-align:justify;'><b>Athos-X</b>, o poderoso Titã da mitologia, personifica a força monumental e a resistência inabalável.</p>" +
                "<p style='text-align:justify;'>Assim como ele ergueu montanhas ou as próprias se tornaram seu corpo, a <b>EITECH Desenvolvimento</b> se inspira " +
"nessa grandiosidade para construir soluções.</p> "
                + "<p style='text-align:justify;'>Na tecnologia, <b>Athos-X</b> representa o desafio de erguer " +
"sistemas robustos, de superar obstáculos técnicos que parecem intransponíveis e de criar infraestruturas " +
"digitais tão sólidas quanto uma montanha.</p>"
                + "<p style='text-align:justify;'>É a personificação do poder computacional que transforma dados " +
"em conhecimento, da engenharia que desbrava novos caminhos e da inovação que molda paisagens digitais.</p>" +
"<p style='text-align:justify;'>Em essência, a <b>EITECH</b> se conecta a <b>Athos-X</b> na missão de fornecer a força e a estabilidade necessárias " +
"para que seus projetos de automação não apenas funcionem, mas dominem o cenário, resistindo ao tempo e " +
"impulsionando o futuro com poder e resiliência.</p>"
                + "</body></html>");
    }
    
    private void insereVersao(){
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html>"
                + "<p style='text-align:left; color:#8B0000; font-size:12px; margin-top:0px; margin-bottom:0px;'><b>Versão: 1.0</b></p>"
                + "<p style='text-align:left; color:#000080; font-size:12px; margin-top:0px; margin-bottom:0px;'><b>Desenvolvido por: Eric Tensol Vieira </b></p>"
                + "<h4 style='text-align:left; color:#000000; font-size:12px; margin-top:0px; margin-bottom:0px;'>CONTATOS</h4>"
                + "<p style='text-align:left; color:#000080; font-size:12px; margin-top:0px; margin-bottom:0px;'>Telefone: <b>(31) 99578-5307</b></p>"
                + "<p style='text-align:left; color:#000080; font-size:12px; margin-top:0px; margin-bottom:0px;'>Site: <b>www.eitech.com.br</b></p>"
        + "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTextoSobre = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pTextoSobre.setEditable(false);
        pTextoSobre.setBorder(null);
        jScrollPane1.setViewportView(pTextoSobre);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/digimaxx/icones/logo_gemini.png"))); // NOI18N

        jScrollPane2.setBorder(null);

        jTextPane1.setBorder(null);
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane pTextoSobre;
    // End of variables declaration//GEN-END:variables
}
